import {
  ArrowDownRight,
  ArrowUpRight,
  Bell,
  Calendar,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  Clock3,
  Columns3,
  Eye,
  FileText,
  KeyRound,
  LayoutDashboard,
  List,
  ListOrdered,
  LogOut,
  MoreVertical,
  Palette,
  Pencil,
  PlusCircle,
  Settings,
  Shapes,
  Trash,
  User,
  Users,
  Wallet,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export type Icon = LucideIcon;

export {
  ArrowDownRight as IconArrowDownRight,
  ArrowUpRight as IconArrowUpRight,
  Bell as IconBell,
  Calendar as IconCalendar,
  CheckCircle as IconCheck,
  ChevronDown as IconChevronDown,
  ChevronLeft as IconChevronLeft,
  ChevronRight as IconChevronRight,
  ChevronsLeft as IconChevronsLeft,
  ChevronsRight as IconChevronsRight,
  Clock3 as IconClockHour4,
  Columns3 as IconLayoutColumns,
  Eye as IconEye,
  FileText as IconFileDescription,
  KeyRound as IconKey,
  LayoutDashboard as IconDashboard,
  List as IconList,
  ListOrdered as IconListDetails,
  LogOut as IconLogout,
  MoreVertical as IconDotsVertical,
  Palette as IconPalette,
  Pencil as IconPencil,
  PlusCircle as IconCirclePlusFilled,
  Settings as IconSettings,
  Settings as IconSettingsCog,
  Shapes as IconCategory,
  Trash as IconTrash,
  User as IconUser,
  Users as IconUsers,
  Wallet as IconWallet,
};
