import { User } from "@/lib/schemas";

export const userTestData: User[] = [
  {
    id: "u-1",
    name: "川野辺 旭",
    email: "asahi@example.com",
    role: "admin",
    status: "active",
    joinedAt: "2025-01-10",
    lastLogin: "2025-04-15",
  },
  {
    id: "u-2",
    name: "山田花子",
    email: "hanako@example.com",
    role: "manager",
    status: "active",
    joinedAt: "2025-02-01",
    lastLogin: "2025-04-14",
  },
  {
    id: "u-3",
    name: "鈴木太郎",
    email: "taro@example.com",
    role: "member",
    status: "invited",
    joinedAt: "2025-03-10",
    lastLogin: null,
  },
  {
    id: "u-4",
    name: "佐藤二郎",
    email: "jiro@example.com",
    role: "viewer",
    status: "suspended",
    joinedAt: "2025-01-15",
    lastLogin: "2025-03-01",
  },
  {
    id: "u-5",
    name: "高橋 由紀",
    email: "yuki.takahashi@example.com",
    role: "manager",
    status: "active",
    joinedAt: "2025-02-12",
    lastLogin: "2025-04-10",
  },
  {
    id: "u-6",
    name: "佐々木 翔",
    email: "sho.sasaki@example.com",
    role: "member",
    status: "active",
    joinedAt: "2025-03-05",
    lastLogin: "2025-04-12",
  },
  {
    id: "u-7",
    name: "伊藤 未来",
    email: "miku.ito@example.com",
    role: "viewer",
    status: "invited",
    joinedAt: "2025-03-20",
    lastLogin: null,
  },
  {
    id: "u-8",
    name: "小林 拓海",
    email: "takumi.k@example.com",
    role: "member",
    status: "active",
    joinedAt: "2025-01-22",
    lastLogin: "2025-04-11",
  },
  {
    id: "u-9",
    name: "中村 里奈",
    email: "rina.nakamura@example.com",
    role: "viewer",
    status: "active",
    joinedAt: "2025-02-18",
    lastLogin: "2025-04-09",
  },
  {
    id: "u-10",
    name: "松本 大地",
    email: "daichi.matsumoto@example.com",
    role: "admin",
    status: "active",
    joinedAt: "2025-01-05",
    lastLogin: "2025-04-15",
  },
  {
    id: "u-11",
    name: "加藤 彩乃",
    email: "ayano.k@example.com",
    role: "manager",
    status: "active",
    joinedAt: "2025-03-12",
    lastLogin: "2025-04-13",
  },
  {
    id: "u-12",
    name: "吉田 陽斗",
    email: "haruto.yoshida@example.com",
    role: "member",
    status: "suspended",
    joinedAt: "2025-02-08",
    lastLogin: "2025-03-18",
  },
  {
    id: "u-13",
    name: "清水 美咲",
    email: "misaki.shimizu@example.com",
    role: "viewer",
    status: "active",
    joinedAt: "2025-03-28",
    lastLogin: null,
  },
  {
    id: "u-14",
    name: "斎藤 健",
    email: "ken.saito@example.com",
    role: "member",
    status: "active",
    joinedAt: "2025-01-28",
    lastLogin: "2025-04-07",
  },
  {
    id: "u-15",
    name: "原田 美月",
    email: "mizuki.harada@example.com",
    role: "viewer",
    status: "invited",
    joinedAt: "2025-04-01",
    lastLogin: null,
  },
  {
    id: "u-16",
    name: "岡田 慎",
    email: "shin.okada@example.com",
    role: "member",
    status: "active",
    joinedAt: "2025-02-25",
    lastLogin: "2025-04-08",
  },
  {
    id: "u-17",
    name: "森田 菜々",
    email: "nana.morita@example.com",
    role: "viewer",
    status: "active",
    joinedAt: "2025-03-02",
    lastLogin: "2025-04-05",
  },
  {
    id: "u-18",
    name: "藤田 颯",
    email: "hayate.fujita@example.com",
    role: "member",
    status: "suspended",
    joinedAt: "2025-01-18",
    lastLogin: "2025-03-22",
  },
  {
    id: "u-19",
    name: "石川 花",
    email: "hana.ishikawa@example.com",
    role: "manager",
    status: "active",
    joinedAt: "2025-02-14",
    lastLogin: "2025-04-06",
  },
  {
    id: "u-20",
    name: "三浦 太一",
    email: "taichi.miura@example.com",
    role: "member",
    status: "active",
    joinedAt: "2025-03-08",
    lastLogin: "2025-04-10",
  },
  {
    id: "u-21",
    name: "島田 紗季",
    email: "saki.shimada@example.com",
    role: "viewer",
    status: "invited",
    joinedAt: "2025-04-05",
    lastLogin: null,
  },
  {
    id: "u-22",
    name: "小川 陽子",
    email: "yoko.ogawa@example.com",
    role: "member",
    status: "active",
    joinedAt: "2025-02-03",
    lastLogin: "2025-04-04",
  },
  {
    id: "u-23",
    name: "村上 蒼",
    email: "ao.murakami@example.com",
    role: "viewer",
    status: "suspended",
    joinedAt: "2025-01-30",
    lastLogin: "2025-03-15",
  },
  {
    id: "u-24",
    name: "福田 理沙",
    email: "risa.fukuda@example.com",
    role: "manager",
    status: "active",
    joinedAt: "2025-03-18",
    lastLogin: "2025-04-11",
  },
  {
    id: "u-25",
    name: "西川 悠真",
    email: "yuma.nishikawa@example.com",
    role: "member",
    status: "active",
    joinedAt: "2025-02-20",
    lastLogin: "2025-04-09",
  },
  {
    id: "u-26",
    name: "上田 真央",
    email: "mao.ueda@example.com",
    role: "viewer",
    status: "active",
    joinedAt: "2025-03-25",
    lastLogin: null,
  },
  {
    id: "u-27",
    name: "竹内 悠",
    email: "yu.takeuchi@example.com",
    role: "member",
    status: "invited",
    joinedAt: "2025-04-08",
    lastLogin: null,
  },
  {
    id: "u-28",
    name: "谷口 綾",
    email: "aya.taniguchi@example.com",
    role: "member",
    status: "active",
    joinedAt: "2025-02-27",
    lastLogin: "2025-04-06",
  },
  {
    id: "u-29",
    name: "橋本 悠斗",
    email: "yuto.hashimoto@example.com",
    role: "viewer",
    status: "active",
    joinedAt: "2025-03-15",
    lastLogin: "2025-04-12",
  },
  {
    id: "u-30",
    name: "黒田 美音",
    email: "mione.kuroda@example.com",
    role: "member",
    status: "active",
    joinedAt: "2025-01-27",
    lastLogin: "2025-04-13",
  },
];
